name: ai_resume_analyzer
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  file_picker: ^10.1.2
  syncfusion_flutter_pdfviewer: ^29.1.41
  path_provider: ^2.1.5
  open_file: ^3.5.10
  pdf: ^3.11.3
  pdfx: ^2.9.1
  flutter_dotenv: ^5.2.1
  animations: ^2.0.11
  lottie: ^3.3.1
  flutter_animate: ^4.5.2
  animated_text_kit: ^4.2.3
  responsive_builder: ^0.7.1
  google_fonts: ^6.2.1
  flutter_svg: ^2.1.0
  page_transition: ^2.2.1
  shared_preferences: ^2.5.3
  animated_background: ^2.0.0
  flutter_image: ^4.1.13
  flutter_cube: ^0.1.1
  flutter_3d_controller: ^2.2.0
  xml: ^6.5.0
  archive: ^4.0.7
  provider: ^6.1.5
  http: ^1.4.0
  intl: ^0.20.2
  foundation: ^0.0.5
  animate_do: ^4.2.0
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  google_sign_in: ^6.3.0
  logging: ^1.3.0
  flutter_web_auth_2: ^4.1.0
  webview_windows: ^0.4.0
  equatable: ^2.0.7
  flutter_spinkit: ^5.2.1
  fl_chart: ^1.0.0
  syncfusion_flutter_gauges: ^29.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true

  assets:
    - .env
    - lib/assets/images/ai_resume_analyzer.png
    - lib/assets/animations/resume_animation.json
    - lib/assets/images/background.png
    - lib/assets/images/background_4.png
    - lib/assets/images/google_logo.png
